"""Генерация G-Code: контурная и рельефная обработка."""

import math

from core.geometry import (
    sort_chains_nearest, simplify_chain, offset_chain,
)

try:
    from shapely.geometry import LineString
    HAS_SHAPELY = True
except ImportError:
    HAS_SHAPELY = False

RAPID_RATE = 5000.0  # мм/мин — типичная скорость холостого хода


def format_time_estimate(dist_dict, feedrate, rapid_rate=RAPID_RATE):
    rapid_min = dist_dict["rapid_dist"] / rapid_rate if rapid_rate else 0
    feed_min = dist_dict["feed_dist"] / feedrate if feedrate else 0
    total_min = rapid_min + feed_min
    total_sec = int(total_min * 60)
    if total_sec < 60:
        return f"~{total_sec} сек"
    minutes = total_sec // 60
    seconds = total_sec % 60
    if minutes >= 60:
        hours = minutes // 60
        minutes = minutes % 60
        return f"~{hours} ч {minutes} мин"
    return f"~{minutes} мин {seconds:02d} сек"


def chains_to_gcode(chains, tool_dia, feedrate, final_depth,
                    num_passes, bridge_mode, bridge_size, simplify_eps,
                    safe_z=5.0, bridge_z=0.5, spindle_speed=15000):
    """Генерирует G-код из списка контуров.

    Args:
        chains: Список контуров [[(x,y), ...], ...]
        tool_dia: Диаметр инструмента (мм)
        feedrate: Скорость подачи (мм/мин)
        final_depth: Конечная глубина (мм)
        num_passes: Количество проходов
        bridge_mode: Режим мостиков
        bridge_size: Размер мостика (мм)
        simplify_eps: Упрощение контуров (мм)
        safe_z: Безопасная высота (мм)
        bridge_z: Высота мостика (мм)
        spindle_speed: Скорость вращения шпинделя (об/мин)

    Returns:
        tuple: (gcode_string, dist_dict)

    Raises:
        ValueError: При некорректных входных параметрах
    """
    from core.geometry import insert_bridges

    # Валидация параметров
    if not chains:
        raise ValueError("Список контуров пуст")
    if tool_dia <= 0:
        raise ValueError(f"Диаметр фрезы должен быть > 0, получено: {tool_dia}")
    if feedrate <= 0:
        raise ValueError(f"Подача должна быть > 0, получено: {feedrate}")
    if final_depth <= 0:
        raise ValueError(f"Глубина должна быть > 0, получено: {final_depth}")
    if num_passes < 1:
        raise ValueError(f"Число проходов должно быть >= 1, получено: {num_passes}")
    if safe_z <= 0:
        raise ValueError(f"Safe Z должен быть > 0, получено: {safe_z}")
    if bridge_size < 0:
        raise ValueError(f"Размер мостика должен быть >= 0, получено: {bridge_size}")
    if simplify_eps < 0:
        raise ValueError(f"Упрощение должно быть >= 0, получено: {simplify_eps}")
    if spindle_speed < 0:
        raise ValueError(f"Скорость шпинделя должна быть >= 0, получено: {spindle_speed}")

    offset = tool_dia / 2.0
    lines = [
        "; Generated by PictureToG-Code",
        f"; Tool diameter: {tool_dia} mm  Feedrate: {feedrate} mm/min",
        f"; Final depth: {final_depth} mm  Passes: {num_passes}",
        f"; Spindle speed: {spindle_speed} RPM",
        "G21        ; mm",
        "G90        ; absolute",
        "G17        ; XY plane",
        f"G0 Z{safe_z:.2f}",
        "G0 X0 Y0",
        "M03",
        f"S{spindle_speed:.0f}",
        "",
    ]

    cur_x, cur_y, cur_z = 0.0, 0.0, safe_z
    cur_f = None
    rapid_dist = 0.0
    feed_dist = 0.0

    pass_depths = []
    if num_passes <= 1:
        pass_depths = [final_depth]
    else:
        step = final_depth / num_passes
        for p in range(1, num_passes + 1):
            pass_depths.append(round(step * p, 4))

    chains = sort_chains_nearest(chains)

    for chain in chains:
        chain = simplify_chain(chain, simplify_eps)
        if len(chain) < 2:
            continue

        offset_chains = offset_chain(chain, -offset) if HAS_SHAPELY else [chain]

        for oc in offset_chains:
            if len(oc) < 2:
                continue

            for depth in pass_depths:
                is_last_pass = (depth == pass_depths[-1])

                if bridge_mode and is_last_pass:
                    segs = insert_bridges(oc, bridge_size)
                else:
                    segs = [(oc, False)]

                x0, y0 = oc[0]

                lines.append(f"G0 Z{safe_z:.2f}")
                rapid_dist += abs(safe_z - cur_z)
                cur_z = safe_z

                lines.append(f"G0 X{x0:.2f} Y{y0:.2f}")
                rapid_dist += math.hypot(x0 - cur_x, y0 - cur_y)
                cur_x, cur_y = x0, y0

                z_val = round(-depth, 2)
                f_val = round(feedrate, 1)
                parts = ["G1"]
                parts.append(f"Z{z_val:.2f}")
                feed_dist += abs(z_val - cur_z)
                cur_z = z_val
                parts.append(f"F{f_val:.1f}")
                cur_f = f_val
                lines.append(" ".join(parts))

                first_pt = True
                for (seg, is_bridge) in segs:
                    if is_bridge:
                        z = round(bridge_z, 2)
                    else:
                        z = round(-depth, 2)
                    for pt in seg:
                        if first_pt:
                            first_pt = False
                            continue
                        nx, ny = pt[0], pt[1]
                        feed_dist += math.hypot(nx - cur_x, ny - cur_y) + abs(z - cur_z)
                        parts = [f"G1 X{nx:.2f} Y{ny:.2f}"]
                        if z != cur_z:
                            parts.append(f"Z{z:.2f}")
                            cur_z = z
                        if f_val != cur_f:
                            parts.append(f"F{f_val:.1f}")
                            cur_f = f_val
                        lines.append(" ".join(parts))
                        cur_x, cur_y = nx, ny

    rapid_dist += abs(safe_z - cur_z)
    rapid_dist += math.hypot(cur_x, cur_y)
    lines += ["", "M05", f"G0 Z{safe_z:.2f}", "G0 X0 Y0", "M30  ; end"]

    dist_dict = {"rapid_dist": rapid_dist, "feed_dist": feed_dist}
    return "\n".join(lines), dist_dict


def heightmap_to_gcode(heightmap, tool_dia, stepover_pct, max_depth,
                       feedrate, plunge_feed, safe_z, output_w, output_h,
                       strategy="Зигзаг", spindle_speed=15000):
    """Генерирует растровый G-code по карте высот.

    Args:
        heightmap: Карта высот (numpy array)
        tool_dia: Диаметр инструмента (мм)
        stepover_pct: Перекрытие дорожек (% диаметра)
        max_depth: Максимальная глубина (мм)
        feedrate: Скорость подачи (мм/мин)
        plunge_feed: Скорость врезания (мм/мин)
        safe_z: Безопасная высота (мм)
        output_w: Ширина вывода (мм)
        output_h: Высота вывода (мм)
        strategy: Стратегия обработки ("Зигзаг" или "Однонаправленный")
        spindle_speed: Скорость вращения шпинделя (об/мин)

    Returns:
        tuple: (gcode_string, dist_dict)

    Raises:
        ValueError: При некорректных входных параметрах
    """
    # Валидация параметров
    if heightmap is None:
        raise ValueError("Карта высот не предоставлена")
    if tool_dia <= 0:
        raise ValueError(f"Диаметр фрезы должен быть > 0, получено: {tool_dia}")
    if stepover_pct <= 0 or stepover_pct > 100:
        raise ValueError(f"Перекрытие должно быть в диапазоне (0, 100], получено: {stepover_pct}")
    if max_depth <= 0:
        raise ValueError(f"Максимальная глубина должна быть > 0, получено: {max_depth}")
    if feedrate <= 0:
        raise ValueError(f"Подача должна быть > 0, получено: {feedrate}")
    if plunge_feed <= 0:
        raise ValueError(f"Подача врезания должна быть > 0, получено: {plunge_feed}")
    if safe_z <= 0:
        raise ValueError(f"Safe Z должен быть > 0, получено: {safe_z}")
    if output_w <= 0:
        raise ValueError(f"Ширина вывода должна быть > 0, получено: {output_w}")
    if output_h <= 0:
        raise ValueError(f"Высота вывода должна быть > 0, получено: {output_h}")
    if strategy not in ("Зигзаг", "Однонаправленный"):
        raise ValueError(f"Неизвестная стратегия: {strategy}. Допустимы: Зигзаг, Однонаправленный")
    if spindle_speed < 0:
        raise ValueError(f"Скорость шпинделя должна быть >= 0, получено: {spindle_speed}")

    img_h, img_w = heightmap.shape[:2]
    if img_w == 0 or img_h == 0:
        raise ValueError("Карта высот имеет нулевые размеры")
    step = tool_dia * stepover_pct / 100.0
    if step <= 0:
        step = tool_dia * 0.4

    # масштаб пиксель → мм
    scale_x = output_w / img_w
    scale_y = output_h / img_h

    # шаг сэмплирования в пикселях
    px_step_x = max(1, int(round(step / scale_x)))
    px_step_y = max(1, int(round(step / scale_y)))

    strategy_comment = f"Strategy: {strategy}"
    if strategy == "Однонаправленный":
        strategy_comment += " (без зигзага)"
    else:
        strategy_comment += " (zigzag)"

    lines = [
        "; Generated by PictureToG-Code (Relief mode)",
        f"; Tool diameter: {tool_dia} mm  Stepover: {stepover_pct}%",
        f"; Max depth: {max_depth} mm  Feedrate: {feedrate} mm/min",
        f"; Output size: {output_w:.2f} x {output_h:.2f} mm",
        f"; {strategy_comment}",
        f"; Spindle speed: {spindle_speed} RPM",
        "G21        ; mm",
        "G90        ; absolute",
        "G17        ; XY plane",
        f"G0 Z{safe_z:.2f}",
        "G0 X0 Y0",
        "M03",
        f"S{spindle_speed:.0f}",
        "",
    ]

    cur_x, cur_y, cur_z = 0.0, 0.0, safe_z
    cur_f = None
    rapid_dist = 0.0
    feed_dist = 0.0
    row_idx = 0

    py = 0
    while py < img_h:
        y_mm = output_h - py * scale_y  # Y вверх

        # Определяем направление строки в зависимости от стратегии
        if strategy == "Однонаправленный":
            px_range = range(0, img_w, px_step_x)
        else:
            # Зигзаг
            if row_idx % 2 == 0:
                px_range = range(0, img_w, px_step_x)
            else:
                px_range = range(img_w - 1, -1, -px_step_x)

        first_in_row = True
        for px in px_range:
            px_clamped = min(px, img_w - 1)
            brightness = float(heightmap[min(py, img_h - 1), px_clamped])
            z_val = round(-max_depth * (1.0 - brightness / 255.0), 2)
            x_mm = round(px_clamped * scale_x, 2)
            y_mm_r = round(y_mm, 2)

            if first_in_row:
                # Подъём + перемещение к началу строки
                lines.append(f"G0 Z{safe_z:.2f}")
                rapid_dist += abs(safe_z - cur_z)
                cur_z = safe_z

                lines.append(f"G0 X{x_mm:.2f} Y{y_mm_r:.2f}")
                rapid_dist += math.hypot(x_mm - cur_x, y_mm_r - cur_y)
                cur_x, cur_y = x_mm, y_mm_r

                # Врезание
                f_used = round(plunge_feed, 1)
                lines.append(f"G1 Z{z_val:.2f} F{f_used:.1f}")
                feed_dist += abs(z_val - cur_z)
                cur_z = z_val
                cur_f = f_used
                first_in_row = False
            else:
                # Рабочий ход
                dz = z_val - cur_z
                if dz < -0.01:
                    f_needed = round(plunge_feed, 1)
                else:
                    f_needed = round(feedrate, 1)

                feed_dist += math.hypot(x_mm - cur_x, y_mm_r - cur_y) + abs(dz)

                parts = [f"G1 X{x_mm:.2f} Y{y_mm_r:.2f}"]
                if z_val != cur_z:
                    parts.append(f"Z{z_val:.2f}")
                    cur_z = z_val
                if f_needed != cur_f:
                    parts.append(f"F{f_needed:.1f}")
                    cur_f = f_needed
                lines.append(" ".join(parts))
                cur_x, cur_y = x_mm, y_mm_r

        row_idx += 1
        py += px_step_y

    rapid_dist += abs(safe_z - cur_z)
    rapid_dist += math.hypot(cur_x, cur_y)
    lines += ["", "M05", f"G0 Z{safe_z:.2f}", "G0 X0 Y0", "M30  ; end"]

    dist_dict = {"rapid_dist": rapid_dist, "feed_dist": feed_dist}
    return "\n".join(lines), dist_dict
