/**
 * GCodeGenerator — Генерация G-кода
 * Аналог core/gcode.py
 * 
 * Реализует:
 * - Конвертацию контуров в G-код (chains_to_gcode)
 * - Конвертацию карты высот в G-код (heightmap_to_gcode)
 * - Оценку времени обработки
 */

class GCodeGenerator {
    static RAPID_RATE = 5000.0; // мм/мин — скорость холостого хода

    /**
     * Форматирование оценки времени
     * @param {Object} distDict {rapid_dist, feed_dist}
     * @param {number} feedrate 
     * @param {number} rapidRate 
     * @returns {string}
     */
    static formatTimeEstimate(distDict, feedrate, rapidRate = GCodeGenerator.RAPID_RATE) {
        const rapidMin = rapidRate ? distDict.rapid_dist / rapidRate : 0;
        const feedMin = feedrate ? distDict.feed_dist / feedrate : 0;
        const totalMin = rapidMin + feedMin;
        const totalSec = Math.floor(totalMin * 60);
        
        if (totalSec < 60) {
            return `~${totalSec} сек`;
        }
        
        const minutes = Math.floor(totalSec / 60);
        const seconds = totalSec % 60;
        
        if (minutes >= 60) {
            const hours = Math.floor(minutes / 60);
            const mins = minutes % 60;
            return `~${hours} ч ${mins} мин`;
        }
        
        return `~${minutes} мин ${seconds.toString().padStart(2, '0')} сек`;
    }

    /**
     * Генерирует G-код из списка контуров.
     * КОНТУРНАЯ РЕЗКА — фреза проходит по каждому контуру ОДИН РАЗ.
     *
     * Алгоритм:
     * 1. Упростить контуры (RDP)
     * 2. Применить офсет (компенсация диаметра фрезы)
     * 3. Отсортировать контуры (ближайший сосед)
     * 4. Для каждого контура: подъём → перемещение → врезание → обход
     *
     * @param {Array<Array<[number, number]>>} chains
     * @param {Object} params
     * @returns {{gcode: string, distDict: Object}}
     */
    static chainsToGcode(chains, params) {
        const {
            toolDia, feedrate, finalDepth,
            simplifyEps,
            safeZ = 5.0, spindleSpeed = 15000
        } = params;

        const offset = toolDia / 2.0;
        const lines = [
            '; Generated by PictureToG-Code (Web) — Contour mode',
            `; Tool diameter: ${toolDia} mm  Feedrate: ${feedrate} mm/min`,
            `; Final depth: ${finalDepth} mm`,
            `; Spindle speed: ${spindleSpeed} RPM`,
            'G21        ; mm',
            'G90        ; absolute',
            'G17        ; XY plane',
            `G0 Z${safeZ.toFixed(2)}`,
            'G0 X0 Y0',
            'M03',
            `S${spindleSpeed.toFixed(0)}`,
            '',
        ];

        let curX = 0, curY = 0, curZ = safeZ;
        let curF = null;
        let rapidDist = 0;
        let feedDist = 0;

        // 1. Упрощаем контуры
        chains = chains.map(chain => Geometry.simplifyChain(chain, simplifyEps));

        // 2. Применяем офсет (компенсация радиуса фрезы)
        let offsetChains = [];
        for (const chain of chains) {
            if (chain.length < 2) continue;
            const offsetted = Geometry.offsetChain(chain, -offset);
            offsetChains.push(...offsetted);
        }

        // 3. Сортируем контуры (ближайший сосед — минимизируем холостой ход)
        offsetChains = Geometry.sortChainsNearest(offsetChains);

        // 4. Обходим каждый контур ОДИН раз
        for (const oc of offsetChains) {
            if (oc.length < 2) continue;

            const [x0, y0] = oc[0];
            const zVal = parseFloat((-finalDepth).toFixed(2));
            const fVal = parseFloat(feedrate.toFixed(1));

            // Подъём на safeZ
            lines.push(`G0 Z${safeZ.toFixed(2)}`);
            rapidDist += Math.abs(safeZ - curZ);
            curZ = safeZ;

            // Быстрое перемещение к началу контура
            lines.push(`G0 X${x0.toFixed(2)} Y${y0.toFixed(2)}`);
            rapidDist += Math.hypot(x0 - curX, y0 - curY);
            curX = x0;
            curY = y0;

            // Врезание на глубину (один проход)
            const parts = ['G1', `Z${zVal.toFixed(2)}`, `F${fVal.toFixed(1)}`];
            feedDist += Math.abs(zVal - curZ);
            curZ = zVal;
            curF = fVal;
            lines.push(parts.join(' '));

            // Обход контура — все точки, включая замыкающую
            for (let i = 1; i < oc.length; i++) {
                const nx = oc[i][0];
                const ny = oc[i][1];

                feedDist += Math.hypot(nx - curX, ny - curY);

                lines.push(`G1 X${nx.toFixed(2)} Y${ny.toFixed(2)}`);
                curX = nx;
                curY = ny;
            }
        }

        // Завершение
        rapidDist += Math.abs(safeZ - curZ);
        rapidDist += Math.hypot(curX, curY);

        lines.push('');
        lines.push('M05');
        lines.push(`G0 Z${safeZ.toFixed(2)}`);
        lines.push('G0 X0 Y0');
        lines.push('M30  ; end');

        const distDict = { rapid_dist: rapidDist, feed_dist: feedDist };
        return { gcode: lines.join('\n'), distDict };
    }

    /**
     * Генерирует растровый G-код по карте высот
     * @param {Uint8Array} heightmap 
     * @param {number} imgW 
     * @param {number} imgH 
     * @param {Object} params 
     * @returns {{gcode: string, distDict: Object}}
     */
    static heightmapToGcode(heightmap, imgW, imgH, params) {
        const {
            toolDia, stepoverPct, maxDepth, feedrate,
            plungeFeed, safeZ, outputW, outputH,
            strategy = 'Зигзаг', spindleSpeed = 15000
        } = params;

        // Масштаб пиксель → мм
        const scaleX = outputW / imgW;
        const scaleY = outputH / imgH;

        // Шаг дорожки
        const step = toolDia * stepoverPct / 100.0;
        
        // Шаг сэмплирования в пикселях
        const pxStepX = Math.max(1, Math.round(step / scaleX));
        const pxStepY = Math.max(1, Math.round(step / scaleY));

        const strategyComment = strategy === 'Однонаправленный' 
            ? 'Strategy: Однонаправленный (без зигзага)' 
            : 'Strategy: Зигзаг (zigzag)';

        const lines = [
            '; Generated by PictureToG-Code (Relief mode, Web)',
            `; Tool diameter: ${toolDia} mm  Stepover: ${stepoverPct}%`,
            `; Max depth: ${maxDepth} mm  Feedrate: ${feedrate} mm/min`,
            `; Output size: ${outputW.toFixed(2)} x ${outputH.toFixed(2)} mm`,
            `; ${strategyComment}`,
            `; Spindle speed: ${spindleSpeed} RPM`,
            'G21        ; mm',
            'G90        ; absolute',
            'G17        ; XY plane',
            `G0 Z${safeZ.toFixed(2)}`,
            'G0 X0 Y0',
            'M03',
            `S${spindleSpeed.toFixed(0)}`,
            '',
        ];

        let curX = 0, curY = 0, curZ = safeZ;
        let curF = null;
        let rapidDist = 0;
        let feedDist = 0;
        let rowIndex = 0;

        for (let py = 0; py < imgH; py += pxStepY) {
            const yMm = outputH - py * scaleY; // Y вверх

            // Определяем направление строки
            let pxRange;
            if (strategy === 'Однонаправленный') {
                pxRange = [];
                for (let px = 0; px < imgW; px += pxStepX) pxRange.push(px);
            } else {
                // Зигзаг
                if (rowIndex % 2 === 0) {
                    pxRange = [];
                    for (let px = 0; px < imgW; px += pxStepX) pxRange.push(px);
                } else {
                    pxRange = [];
                    for (let px = imgW - 1; px >= 0; px -= pxStepX) pxRange.push(px);
                }
            }

            let firstInRow = true;
            for (const px of pxRange) {
                const pxClamped = Math.min(px, imgW - 1);
                const brightness = heightmap[Math.min(py, imgH - 1) * imgW + pxClamped];
                const zVal = parseFloat((-maxDepth * (1.0 - brightness / 255.0)).toFixed(2));
                const xMm = parseFloat((pxClamped * scaleX).toFixed(2));
                const yMmR = parseFloat(yMm.toFixed(2));

                if (firstInRow) {
                    // Подъём + перемещение к началу строки
                    lines.push(`G0 Z${safeZ.toFixed(2)}`);
                    rapidDist += Math.abs(safeZ - curZ);
                    curZ = safeZ;

                    lines.push(`G0 X${xMm.toFixed(2)} Y${yMmR.toFixed(2)}`);
                    rapidDist += Math.hypot(xMm - curX, yMmR - curY);
                    curX = xMm;
                    curY = yMmR;

                    // Врезание
                    const fUsed = parseFloat(plungeFeed.toFixed(1));
                    lines.push(`G1 Z${zVal.toFixed(2)} F${fUsed.toFixed(1)}`);
                    feedDist += Math.abs(zVal - curZ);
                    curZ = zVal;
                    curF = fUsed;
                    firstInRow = false;
                } else {
                    // Рабочий ход
                    const dz = zVal - curZ;
                    const fNeeded = parseFloat((dz < -0.01 ? plungeFeed : feedrate).toFixed(1));

                    feedDist += Math.hypot(xMm - curX, yMmR - curY) + Math.abs(dz);

                    const parts = [`G1 X${xMm.toFixed(2)} Y${yMmR.toFixed(2)}`];
                    if (zVal !== curZ) {
                        parts.push(`Z${zVal.toFixed(2)}`);
                        curZ = zVal;
                    }
                    if (fNeeded !== curF) {
                        parts.push(`F${fNeeded.toFixed(1)}`);
                        curF = fNeeded;
                    }
                    lines.push(parts.join(' '));
                    curX = xMm;
                    curY = yMmR;
                }
            }

            rowIndex++;
        }

        // Завершение
        rapidDist += Math.abs(safeZ - curZ);
        rapidDist += Math.hypot(curX, curY);
        
        lines.push('');
        lines.push('M05');
        lines.push(`G0 Z${safeZ.toFixed(2)}`);
        lines.push('G0 X0 Y0');
        lines.push('M30  ; end');

        const distDict = { rapid_dist: rapidDist, feed_dist: feedDist };
        return { gcode: lines.join('\n'), distDict };
    }

    /**
     * Подсветка синтаксиса G-кода — возвращает HTML
     * @param {string} gcode
     * @returns {string} HTML
     */
    static highlightGcode(gcode) {
        const lines = gcode.split('\n');
        const highlighted = lines.map(line => {
            const trimmed = line.trim();

            // Пустая строка
            if (trimmed === '') return '';

            // Комментарий (строка начинается с ;)
            if (trimmed.startsWith(';')) {
                return `<span class="gcode-comment">${GCodeGenerator._esc(trimmed)}</span>`;
            }

            // Строка с комментарием в конце
            let mainPart = trimmed;
            let commentPart = '';
            const commentIdx = trimmed.indexOf(';');
            if (commentIdx > 0) {
                mainPart = trimmed.substring(0, commentIdx).trim();
                commentPart = ` <span class="gcode-comment">${GCodeGenerator._esc(trimmed.substring(commentIdx))}</span>`;
            }

            // Разбиваем команду на токены
            const tokens = GCodeGenerator._tokenize(mainPart);
            return tokens + commentPart;
        });

        return highlighted.join('\n');
    }

    /**
     * Экранирование HTML-сущностей
     */
    static _esc(str) {
        return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    /**
     * Токенизация строки G-кода с подсветкой
     */
    static _tokenize(line) {
        const escaped = GCodeGenerator._esc(line);

        // G0, G00
        if (/^G0\b/.test(escaped)) {
            return escaped.replace(/\b(G0)\b/g, '<span class="gcode-g0">$1</span>');
        }

        // G1
        if (/^G1\b/.test(escaped)) {
            return escaped.replace(/\b(G1)\b/g, '<span class="gcode-g1">$1</span>');
        }

        // G2, G3
        if (/^G[23]\b/.test(escaped)) {
            return escaped.replace(/\b(G[23])\b/g, '<span class="gcode-g2">$1</span>');
        }

        // Header lines: G21, G90, G17
        let result = escaped;
        result = result.replace(/\b(G21|G90|G17)\b/g, '<span class="gcode-g21">$1</span>');

        // M-команды
        result = result.replace(/\b(M0[35]|M30)\b/g, '<span class="gcode-m03">$1</span>');

        // Подсветка параметров: X, Y, Z, F, S
        result = result.replace(/\b(X)(-?[\d.]+)/g, '<span class="gcode-x">$1</span>$2');
        result = result.replace(/\b(Y)(-?[\d.]+)/g, '<span class="gcode-y">$1</span>$2');
        result = result.replace(/\b(Z)(-?[\d.]+)/g, '<span class="gcode-z">$1</span>$2');
        result = result.replace(/\b(F)([\d.]+)/g, '<span class="gcode-f">$1</span>$2');
        result = result.replace(/\b(S)([\d.]+)/g, '<span class="gcode-s">$1</span>$2');

        // Строки-заголовки (начинаются с ;)
        if (line.trimStart().startsWith(';')) {
            return `<span class="gcode-comment">${escaped}</span>`;
        }

        return result;
    }
}
