/**
 * GCodeGenerator — Генерация G-кода
 *
 * Контурный режим: только G1 (линии).
 * G2/G3 удалены — оставлено сглаживание Chaikin + ре-сэмплинг
 * для получения плавного результата без дуговых команд.
 */

class GCodeGenerator {
    static RAPID_RATE = 5000.0;

    static formatTimeEstimate(distDict, feedrate, rapidRate = GCodeGenerator.RAPID_RATE) {
        const rapidMin = rapidRate ? distDict.rapid_dist / rapidRate : 0;
        const feedMin = feedrate ? distDict.feed_dist / feedrate : 0;
        const totalSec = Math.floor((rapidMin + feedMin) * 60);
        if (totalSec < 60) return `~${totalSec} сек`;
        const minutes = Math.floor(totalSec / 60);
        const seconds = totalSec % 60;
        if (minutes >= 60) {
            return `~${Math.floor(minutes / 60)} ч ${minutes % 60} мин`;
        }
        return `~${minutes} мин ${seconds.toString().padStart(2, '0')} сек`;
    }

    /**
     * Генерирует G-код из списка контуров (G1 линии).
     *
     * @param {Array<Array<[number, number]>>} chains
     * @param {Object} params
     * @returns {{gcode: string, distDict: Object}}
     */
    static chainsToGcode(chains, params) {
        const {
            toolDia, feedrate, finalDepth,
            simplifyEps,
            safeZ = 5.0, spindleSpeed = 15000,
        } = params;

        const offset = toolDia / 2.0;

        const lines = [
            '; Generated by PictureToG-Code (Web) — Contour mode',
            '; Contour mode: G1 linear (smooth via Chaikin)',
            `; Tool diameter: ${toolDia} mm  Feedrate: ${feedrate} mm/min`,
            `; Final depth: ${finalDepth} mm`,
            `; Spindle speed: ${spindleSpeed} RPM`,
            'G21        ; mm',
            'G90        ; absolute',
            'G17        ; XY plane',
            `G0 Z${safeZ.toFixed(3)}`,
            'G0 X0 Y0',
            'M03',
            `S${spindleSpeed.toFixed(0)}`,
            '',
        ];

        let curX = 0, curY = 0, curZ = safeZ;
        let rapidDist = 0, feedDist = 0;

        // Упрощение (если задан simplifyEps — дополнительный RDP поверх уже сглаженного)
        chains = chains.map(chain => Geometry.simplifyChain(chain, simplifyEps));

        // Офсет (компенсация радиуса фрезы)
        let offsetChains = [];
        for (const chain of chains) {
            if (chain.length < 2) continue;
            offsetChains.push(...Geometry.offsetChain(chain, -offset));
        }

        // Сортировка — минимизируем холостой ход
        offsetChains = Geometry.sortChainsNearest(offsetChains);

        for (const oc of offsetChains) {
            if (oc.length < 2) continue;

            const [x0, y0] = oc[0];
            const zVal = -finalDepth;
            const fVal = feedrate;

            // Подъём
            lines.push(`G0 Z${safeZ.toFixed(3)}`);
            rapidDist += Math.abs(safeZ - curZ);
            curZ = safeZ;

            // Переезд к началу контура
            lines.push(`G0 X${x0.toFixed(3)} Y${y0.toFixed(3)}`);
            rapidDist += Math.hypot(x0 - curX, y0 - curY);
            curX = x0; curY = y0;

            // Врезание
            lines.push(`G1 Z${zVal.toFixed(3)} F${fVal.toFixed(1)}`);
            feedDist += Math.abs(zVal - curZ);
            curZ = zVal;

            // Обход контура — только XY, F не повторяем
            for (let i = 1; i < oc.length; i++) {
                const nx = oc[i][0], ny = oc[i][1];
                const d = Math.hypot(nx - curX, ny - curY);
                if (d < 0.001) continue; // пропускаем дубликаты
                feedDist += d;
                lines.push(`G1 X${nx.toFixed(3)} Y${ny.toFixed(3)}`);
                curX = nx; curY = ny;
            }
        }

        // Завершение
        rapidDist += Math.abs(safeZ - curZ) + Math.hypot(curX, curY);
        lines.push('');
        lines.push('M05');
        lines.push(`G0 Z${safeZ.toFixed(3)}`);
        lines.push('G0 X0 Y0');
        lines.push('M30  ; end');

        return {
            gcode: lines.join('\n'),
            distDict: { rapid_dist: rapidDist, feed_dist: feedDist }
        };
    }

    // ─── Рельеф (без изменений) ───────────────────────────────────────────────

    static heightmapToGcode(heightmap, imgW, imgH, params) {
        const {
            toolDia, stepoverPct, maxDepth, feedrate,
            plungeFeed, safeZ, outputW, outputH,
            strategy = 'Зигзаг', spindleSpeed = 15000
        } = params;

        const scaleX = outputW / imgW;
        const scaleY = outputH / imgH;
        const step = toolDia * stepoverPct / 100.0;
        const pxStepX = Math.max(1, Math.round(step / scaleX));
        const pxStepY = Math.max(1, Math.round(step / scaleY));

        const lines = [
            '; Generated by PictureToG-Code (Relief mode, Web)',
            `; Tool diameter: ${toolDia} mm  Stepover: ${stepoverPct}%`,
            `; Max depth: ${maxDepth} mm  Feedrate: ${feedrate} mm/min`,
            `; Output size: ${outputW.toFixed(2)} x ${outputH.toFixed(2)} mm`,
            `; Strategy: ${strategy}`,
            `; Spindle speed: ${spindleSpeed} RPM`,
            'G21        ; mm',
            'G90        ; absolute',
            'G17        ; XY plane',
            `G0 Z${safeZ.toFixed(2)}`,
            'G0 X0 Y0',
            'M03',
            `S${spindleSpeed.toFixed(0)}`,
            '',
        ];

        let curX = 0, curY = 0, curZ = safeZ;
        let curF = null;
        let rapidDist = 0, feedDist = 0;
        let rowIndex = 0;

        for (let py = 0; py < imgH; py += pxStepY) {
            const yMm = outputH - py * scaleY;
            let pxRange = [];
            if (strategy === 'Однонаправленный') {
                for (let px = 0; px < imgW; px += pxStepX) pxRange.push(px);
            } else {
                if (rowIndex % 2 === 0) {
                    for (let px = 0; px < imgW; px += pxStepX) pxRange.push(px);
                } else {
                    for (let px = imgW - 1; px >= 0; px -= pxStepX) pxRange.push(px);
                }
            }

            let firstInRow = true;
            for (const px of pxRange) {
                const pxC = Math.min(px, imgW - 1);
                const brightness = heightmap[Math.min(py, imgH - 1) * imgW + pxC];
                const zVal = parseFloat((-maxDepth * (1 - brightness / 255)).toFixed(2));
                const xMm = parseFloat((pxC * scaleX).toFixed(2));
                const yMmR = parseFloat(yMm.toFixed(2));

                if (firstInRow) {
                    lines.push(`G0 Z${safeZ.toFixed(2)}`);
                    rapidDist += Math.abs(safeZ - curZ); curZ = safeZ;
                    lines.push(`G0 X${xMm} Y${yMmR}`);
                    rapidDist += Math.hypot(xMm - curX, yMmR - curY);
                    curX = xMm; curY = yMmR;
                    const fUsed = parseFloat(plungeFeed.toFixed(1));
                    lines.push(`G1 Z${zVal} F${fUsed}`);
                    feedDist += Math.abs(zVal - curZ);
                    curZ = zVal; curF = fUsed;
                    firstInRow = false;
                } else {
                    const dz = zVal - curZ;
                    const fNeeded = parseFloat((dz < -0.01 ? plungeFeed : feedrate).toFixed(1));
                    feedDist += Math.hypot(xMm - curX, yMmR - curY) + Math.abs(dz);
                    const parts = [`G1 X${xMm} Y${yMmR}`];
                    if (zVal !== curZ) { parts.push(`Z${zVal}`); curZ = zVal; }
                    if (fNeeded !== curF) { parts.push(`F${fNeeded}`); curF = fNeeded; }
                    lines.push(parts.join(' '));
                    curX = xMm; curY = yMmR;
                }
            }
            rowIndex++;
        }

        rapidDist += Math.abs(safeZ - curZ) + Math.hypot(curX, curY);
        lines.push('');
        lines.push('M05');
        lines.push(`G0 Z${safeZ.toFixed(2)}`);
        lines.push('G0 X0 Y0');
        lines.push('M30  ; end');

        return { gcode: lines.join('\n'), distDict: { rapid_dist: rapidDist, feed_dist: feedDist } };
    }

    // ─── Подсветка синтаксиса ────────────────────────────────────────────────

    static highlightGcode(gcode) {
        return gcode.split('\n').map(line => {
            const t = line.trim();
            if (!t) return '';
            if (t.startsWith(';'))
                return `<span class="gcode-comment">${GCodeGenerator._esc(t)}</span>`;

            let main = t, comment = '';
            const ci = t.indexOf(';');
            if (ci > 0) {
                main = t.substring(0, ci).trim();
                comment = ` <span class="gcode-comment">${GCodeGenerator._esc(t.substring(ci))}</span>`;
            }
            return GCodeGenerator._tokenize(main) + comment;
        }).join('\n');
    }

    static _esc(s) {
        return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    static _tokenize(line) {
        const e = GCodeGenerator._esc(line);
        if (/^G0\b/.test(e)) return e.replace(/\b(G0)\b/g, '<span class="gcode-g0">$1</span>');
        if (/^G1\b/.test(e)) return e.replace(/\b(G1)\b/g, '<span class="gcode-g1">$1</span>');
        if (/^G[23]\b/.test(e)) return e.replace(/\b(G[23])\b/g, '<span class="gcode-g2">$1</span>');
        let r = e;
        r = r.replace(/\b(G21|G90|G17)\b/g, '<span class="gcode-g21">$1</span>');
        r = r.replace(/\b(M0[35]|M30)\b/g, '<span class="gcode-m03">$1</span>');
        r = r.replace(/\b(X)(-?[\d.]+)/g, '<span class="gcode-x">$1</span>$2');
        r = r.replace(/\b(Y)(-?[\d.]+)/g, '<span class="gcode-y">$1</span>$2');
        r = r.replace(/\b(Z)(-?[\d.]+)/g, '<span class="gcode-z">$1</span>$2');
        r = r.replace(/\b(F)([\d.]+)/g, '<span class="gcode-f">$1</span>$2');
        r = r.replace(/\b(S)([\d.]+)/g, '<span class="gcode-s">$1</span>$2');
        return r;
    }
}
